name: Release

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENCE.md"
      - "CODEOWNERS"

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=teampam
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./release.sh
